# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
    
    - name: Grant execute permission to PreliminaryJudge
      run: chmod +x ./judge-linux/PreliminaryJudge
      
    # - name: List build directory contents
    #   run: ls -lah ${{github.workspace}}/build

    - name: Run Preliminary Judge
      run: ./judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ./judge-linux/maps/map1.txt

